{
 "title": "Redis",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "targets": [
    {
     "expr": "redis_uptime_in_seconds{addr=\"$addr\"}"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "valueName": "current",
   "targets": [
    {
     "expr": "redis_connected_clients{addr=\"$addr\"}"
    }
   ]
  },
  {
   "title": "Commands Executed / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "repeat": "addr",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total{addr=~\"$addr\"}[5m])"
    }
   ]
  },
  {
   "title": "Hits vs Misses / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{addr=\"$addr\"}[5m])",
     "legendFormat": "hits"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{addr=\"$addr\"}[5m])",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes{addr=~\"$addr\"}",
     "legendFormat": "used"
    },
    {
     "expr": "redis_memory_max_bytes{addr=~\"$addr\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Network I/O",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{addr=\"$addr\"}[5m])",
     "legendFormat": "{{ input }}"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{addr=\"$addr\"}[5m])",
     "legendFormat": "{{ output }}"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{addr=~\"$addr\"}) by (db)",
     "legendFormat": "{{ db }}"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{addr=~\"$addr\"}) - sum (redis_db_keys_expiring{addr=~\"$addr\"})",
     "legendFormat": "not expiring"
    },
    {
     "expr": "sum (redis_db_keys_expiring{addr=~\"$addr\"})",
     "legendFormat": "expiring"
    }
   ]
  },
  {
   "title": "Expired vs Evicted Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{addr=~\"$addr\"}[5m])) by (addr)",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{addr=~\"$addr\"}[5m])) by (addr)",
     "legendFormat": "evicted"
    }
   ]
  },
  {
   "title": "Command Calls / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, irate(redis_command_call_duration_seconds_count{addr=~\"$addr\"} [1m]))",
     "legendFormat": "{{ cmd }}"
    }
   ]
  }
 ]
}